# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven Testing

on:
  workflow_dispatch:
    inputs:
      browsername:
        type: string
        description: 'browser name'
        default: 'chrome'
      testname:
        description: 'enter the regex to run the test'
        type: string
      xmlfilename:
        type: string
        description: 'enter on or xmls to run'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build using testng xml files
      if: ${{inputs.xmlfilename}}
      run: > 
        mvn clean test 
        -DXmlFile=${{inputs.xmlfilename}} 
        -DenableBrowserOptions=true 
        -Dmaven.test.failure.ignore=true

    - name: Build with Maven regex
      if: ${{inputs.testname}}
      run: > 
        mvn clean test 
        -Dtest=${{inputs.testname}} 
        -DbrowserName=${{inputs.browsername}}
        -DenableBrowserOptions=true 
        -Dmaven.test.failure.ignore=true

#     Report generation
#    - name: archive report artifact
#      uses: actions/upload-artifact@v3
#      with:
#        name: sparkHTML
#        path: ./reports/spark.html
